### ISSUE TITLE
Gremlin Server Support

### ISSUE THREAD

**Issue by wolf4ood** [orientechnologies/orientdb-gremlin#114]

**Comment by GabCamarda** [comment]
This would be very much appreciated! You would give devs the possibility to code with clients in different languages and it would also mean that we can use the same interface for multiple vendors.
Thanks!

**Comment by jacques-** [comment]
Would be great to have this! What is the current status?

Seems like it should work, but running into problems: https://stackoverflow.com/questions/45730131/the-database-instance-is-not-set-in-the-current-thread-when-using-gremlin-serv

**Comment by maggiolo00** [comment]
Hi @jacques- 

the support for the Gremlin server is not yet landed and the current `OrientGraph` implementation has not been tested with the Gremlin Server but I guess the observation in the question are right.

The OrientGraph cannot be shared between threads since it holds a `ODatabaseDocument` reference that is not thread safe

**Comment by WolfgangFahl** [comment]
I'd love to see this implemented

**Comment by wolf4ood** [comment]
Hi @WolfgangFahl 

i forgot to close this.

If you  download ODB version 3.0.x tp3 edition it embeds a GremlinServer

https://orientdb.com/download-2/

Thanks
